### ISSUE TITLE
Can you add descriptions of these in Readme? 

### ISSUE THREAD

**Issue by tempsaint** [cmcasey79/canvas-customizations-by-chris#1]
Chris, thank you for your work on developing these. My javascript skills are very lacking so I'm always looking for people like you who develop tweaks to Canvas. It's a nice list of tweaks, but is it possible for you to include a description of each one? Just looking at the code sometimes isn't enough.  Thanks.

**Comment by cmcasey79** [comment]
Thanks for the feedback.  Instead of doing this in the readme (which is an extra area that I will honestly probably forget to update in the future), I added a descriptive comment on the first line of each file.  I hope this helps!

**Comment by tempsaint** [comment]
Great idea. Thanks.
